remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Haptics context]
description: [an excerpt from the initial case study...]
theme: jekyll-theme-midnight
